### PR TITLE
Add new turning options

### PR DESCRIPTION
**Pull request by schneiel**
Dear lr32,

this improves your code in concern of usability and especially concerning SOLID principles (https://en.wikipedia.org/wiki/SOLID)

Props for the project, nevertheless. When if find some time I will make more contributions to "make the code more SOLID". ;)

### CODE REVIEW

**Comment by schneiel** [comment]
Addition: You could argue that three more method are overhead. But the problem is actually that the "Robot" class is way too powerful. In the professional environment, you MOSTLY use 3-4 properties per class at most, and only as few methods as necessary. The class is much too big. Some things have to be outsourced here.

**Comment by Rdeisenroth** [comment]
Hi, this version of FOPBot is not maintained anymore. The current version is here: https://github.com/tudalgo/fopbot

**Comment by schneiel** [comment]
As discussed in private I close the pull request now.

When I find the time I am going to create a pull request in the new repository where I present you how I would change the software design.

Only so much:
- In this state, you do not divide the business logic (Controller) and the Data Model
    - Example, Data Model: https://github.com/lr32/fopbot/blob/0ec979422898afe33621408f550457cbcfd02786/src/fopbot/Robot.java#L229
    - Example, Controller: https://github.com/lr32/fopbot/blob/master/src/fopbot/Robot.java#L358
    
There are other examples where you created methods which can be categorised in similar "Superordinates" and outsourced in new smaller classes. To my mind, the class as it is has not only one responsibility (S in SOLID) but at least three.

**Comment by schneiel** [comment]
I can recommend you this article: https://www.freecodecamp.org/news/solid-principles-for-programming-and-software-design/#:~:text=The%20SOLID%20principles%20of%20object,work%20with%20anywhere%20and%20anytime.

It describes why you should use SOLID and how you do that.

**Comment by lord-dolor** [comment]
ligma

alles trivial hier

**Pull request closed without merging**
